name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        neovim: [stable, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.neovim }}
          neovim: true
      - uses: JohnnyMorganz/stylua-action@v4
        if: matrix.neovim == 'stable'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua plugin tests
      - run: make test
